# Generated by Django 5.1.4 on 2025-11-13 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmpowerReport',
            fields=[
                ('report_id', models.AutoField(primary_key=True, serialize=False)),
                ('report_name', models.CharField(help_text='User-friendly report name', max_length=255)),
                ('project_id', models.CharField(help_text='Project identifier (e.g., SI-54X1)', max_length=100)),
                ('user_initials', models.CharField(help_text="Creator's initials", max_length=10)),
                ('report_type', models.CharField(choices=[('SEC', 'Size Exclusion Chromatography'), ('TITER', 'Titer Analysis'), ('CE-SDS', 'Capillary Electrophoresis SDS'), ('CIEF', 'Capillary Isoelectric Focusing')], default='SEC', max_length=20)),
                ('sample_data', models.JSONField(help_text='Array of sample objects with result_id, sample_name, and group')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'empower_report',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='empower_rep_created_078b19_idx'), models.Index(fields=['report_type'], name='empower_rep_report__6f51f5_idx'), models.Index(fields=['project_id'], name='empower_rep_project_3879fe_idx')],
            },
        ),
    ]
