# Generated by Django 5.1.4 on 2025-11-12 22:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NavigationSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Display name for the navigation section', max_length=100)),
                ('icon', models.CharField(blank=True, help_text="Font Awesome icon class (e.g., 'fa-microscope', 'fa-flask')", max_length=50)),
                ('order', models.IntegerField(default=0, help_text='Display order (lower numbers appear first)')),
                ('is_collapsible', models.BooleanField(default=True, help_text='If False, this section acts as a direct link (no sub-items)')),
                ('url', models.CharField(blank=True, help_text='URL for non-collapsible sections (direct links)', max_length=200)),
                ('is_active', models.BooleanField(default=True, help_text='Show/hide this section')),
            ],
            options={
                'verbose_name': 'Navigation Section',
                'verbose_name_plural': 'Navigation Sections',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='NavigationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Display name for the menu item', max_length=100)),
                ('url', models.CharField(help_text='URL path for this menu item', max_length=200)),
                ('icon', models.CharField(blank=True, help_text="Font Awesome icon class (e.g., 'fa-chart-area')", max_length=50)),
                ('order', models.IntegerField(default=0, help_text='Display order within the section')),
                ('is_active', models.BooleanField(default=True, help_text='Show/hide this menu item')),
                ('description', models.TextField(blank=True, help_text='Optional description for the menu item')),
                ('section', models.ForeignKey(help_text='Parent section for this menu item', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='dashboard.navigationsection')),
            ],
            options={
                'verbose_name': 'Navigation Item',
                'verbose_name_plural': 'Navigation Items',
                'ordering': ['order', 'name'],
            },
        ),
    ]
