# Generated by Django 5.1.4 on 2025-06-24 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plotly_integration', '0101_aktachromatogram_idx_chrom_result_ml_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timeseriesdata',
            options={'managed': True, 'ordering': ['result_id', 'time']},
        ),
        migrations.AddIndex(
            model_name='peakresults',
            index=models.Index(fields=['result_id', 'peak_retention_time'], name='peak_result_result__490ac8_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['analysis_type', 'department', '-report_id'], name='report_analysi_0bf6bf_idx'),
        ),
        migrations.AddIndex(
            model_name='samplemetadata',
            index=models.Index(fields=['sample_type', 'sample_name', '-date_acquired'], name='sample_meta_sample__f2dc79_idx'),
        ),
        migrations.AddIndex(
            model_name='samplemetadata',
            index=models.Index(fields=['sample_set_name', 'sample_prefix'], name='sample_meta_sample__c911bc_idx'),
        ),
        migrations.AddIndex(
            model_name='timeseriesdata',
            index=models.Index(fields=['result_id', 'time'], name='time_series_result__28e03a_idx'),
        ),
    ]
