# Generated by Django 5.1.4 on 2025-07-16 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plotly_integration', '0102_alter_timeseriesdata_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='vicelldata',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='vicelldata',
            name='sample_id',
            field=models.CharField(max_length=100),
        ),
    ]
