# Generated by Django 5.1.4 on 2025-07-26 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plotly_integration', '0103_alter_vicelldata_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cieftimeseries',
            options={'ordering': ['time_min']},
        ),
        migrations.AddIndex(
            model_name='ciefmetadata',
            index=models.Index(fields=['sample_id_full'], name='cief_metada_sample__6d581d_idx'),
        ),
        migrations.AddIndex(
            model_name='ciefmetadata',
            index=models.Index(fields=['acquisition_datetime'], name='cief_metada_acquisi_03569f_idx'),
        ),
        migrations.AddIndex(
            model_name='ciefmetadata',
            index=models.Index(fields=['sample_set_id'], name='cief_metada_sample__b25b2f_idx'),
        ),
        migrations.AddIndex(
            model_name='ciefreport',
            index=models.Index(fields=['date_created'], name='cief_report_date_cr_f1c215_idx'),
        ),
        migrations.AddIndex(
            model_name='ciefreport',
            index=models.Index(fields=['user_id'], name='cief_report_user_id_259693_idx'),
        ),
        migrations.AddIndex(
            model_name='ciefreport',
            index=models.Index(fields=['project_id'], name='cief_report_project_707d5d_idx'),
        ),
        migrations.AddIndex(
            model_name='cieftimeseries',
            index=models.Index(fields=['metadata'], name='cief_time_s_metadat_910e5e_idx'),
        ),
        migrations.AddIndex(
            model_name='cieftimeseries',
            index=models.Index(fields=['time_min'], name='cief_time_s_time_mi_e5aa78_idx'),
        ),
        migrations.AddIndex(
            model_name='cieftimeseries',
            index=models.Index(fields=['metadata', 'time_min'], name='cief_time_s_metadat_937a07_idx'),
        ),
    ]
