# Generated by Django 5.1.4 on 2025-07-26 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plotly_integration', '0104_alter_cieftimeseries_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cesdsreport',
            name='settings',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ciefreport',
            name='settings',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='limsciefresult',
            name='band_pattern',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
