# Generated by Django 5.1.4 on 2025-07-30 18:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plotly_integration', '0105_cesdsreport_settings_ciefreport_settings_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='limscesdsresult',
            name='report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='plotly_integration.cesdsreport'),
        ),
        migrations.AddField(
            model_name='limsciefresult',
            name='report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='plotly_integration.ciefreport'),
        ),
        migrations.AddField(
            model_name='limstiterresult',
            name='report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='plotly_integration.report'),
        ),
    ]
