# Generated by Django 5.1.4 on 2025-08-19 18:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plotly_integration', '0106_limscesdsresult_report_limsciefresult_report_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExperimentalSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('project_id', models.CharField(max_length=255)),
                ('study_type', models.CharField(choices=[('cex', 'CEX Optimization'), ('aex', 'AEX Optimization'), ('hic', 'HIC Study'), ('prota', 'Protein A'), ('custom', 'Custom')], default='custom', max_length=50)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_experimental_sets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'experimental_set',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExperimentalSetData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resin', models.CharField(blank=True, max_length=100)),
                ('cv_ml', models.FloatField(blank=True, null=True, verbose_name='CV (mL)')),
                ('residence_time', models.FloatField(blank=True, null=True, verbose_name='Residence Time (min)')),
                ('elution_condition', models.CharField(blank=True, max_length=200)),
                ('eq', models.CharField(blank=True, max_length=100)),
                ('wash_condition', models.CharField(blank=True, max_length=200)),
                ('load_density', models.FloatField(blank=True, null=True, verbose_name='Load Density (mg/mL)')),
                ('product_required', models.FloatField(blank=True, null=True, verbose_name='Product Required (mg)')),
                ('load_volume', models.FloatField(blank=True, null=True, verbose_name='Load Volume (mL)')),
                ('eluate_volume', models.FloatField(blank=True, null=True, verbose_name='Eluate Volume (mL)')),
                ('eluate_concentration', models.FloatField(blank=True, null=True, verbose_name='Eluate Concentration (mg/mL)')),
                ('eluate_amount', models.FloatField(blank=True, null=True, verbose_name='Eluate Amount (mg)')),
                ('yield_percent', models.FloatField(blank=True, null=True, verbose_name='Yield (%)')),
                ('mp_sec_percent', models.FloatField(blank=True, null=True, verbose_name='% MP SEC')),
                ('ppm_hcp', models.FloatField(blank=True, null=True, verbose_name='PPM HCP')),
                ('ppb_dna', models.FloatField(blank=True, null=True, verbose_name='PPB DNA')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dn_assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plotly_integration.limsdnassignment')),
                ('experimental_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experimental_data', to='plotly_integration.experimentalset')),
            ],
            options={
                'db_table': 'experimental_set_data',
                'ordering': ['dn_assignment__dn'],
                'unique_together': {('experimental_set', 'dn_assignment')},
            },
        ),
    ]
