# Generated by Django 5.1.4 on 2025-08-28 21:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plotly_integration', '0107_add_experimental_set_models'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='USPDasgipExperiment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=500)),
                ('full_name', models.CharField(blank=True, max_length=500, null=True)),
                ('location_name', models.CharField(blank=True, max_length=500, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('state', models.IntegerField(blank=True, null=True)),
                ('version', models.CharField(blank=True, max_length=50, null=True)),
                ('start_timestamp', models.DateTimeField()),
                ('stop_timestamp', models.DateTimeField()),
                ('guid', models.CharField(blank=True, max_length=100, null=True)),
                ('host', models.CharField(blank=True, max_length=255, null=True)),
                ('dasware_version', models.CharField(blank=True, max_length=50, null=True)),
                ('database_version', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'usp_dasgip_experiment',
                'ordering': ['-start_timestamp'],
            },
        ),
        migrations.CreateModel(
            name='USPBioreactorUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_number', models.IntegerField()),
                ('setup_name', models.CharField(max_length=500)),
                ('location_name', models.CharField(blank=True, max_length=500, null=True)),
                ('up_number', models.CharField(blank=True, max_length=100, null=True)),
                ('start_timestamp', models.DateTimeField()),
                ('stop_timestamp', models.DateTimeField()),
                ('guid', models.CharField(blank=True, max_length=100, null=True)),
                ('module_name', models.CharField(blank=True, max_length=500, null=True)),
                ('experiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='plotly_integration.uspdasgipexperiment')),
            ],
            options={
                'db_table': 'usp_bioreactor_unit',
                'ordering': ['unit_number'],
                'unique_together': {('experiment', 'unit_number')},
            },
        ),
        migrations.CreateModel(
            name='USPDasgipFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=500)),
                ('file_path', models.CharField(max_length=1000)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('parsed_date', models.DateTimeField(blank=True, null=True)),
                ('file_size', models.BigIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('uploaded', 'Uploaded'), ('parsing', 'Parsing'), ('parsed', 'Parsed'), ('error', 'Error')], default='uploaded', max_length=50)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'usp_dasgip_file',
                'ordering': ['-upload_date'],
            },
        ),
        migrations.AddField(
            model_name='uspdasgipexperiment',
            name='file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiments', to='plotly_integration.uspdasgipfile'),
        ),
        migrations.CreateModel(
            name='USPParameterTrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track_number', models.IntegerField()),
                ('track_name', models.CharField(max_length=500)),
                ('parameter_name', models.CharField(max_length=500)),
                ('location_name', models.CharField(blank=True, max_length=500, null=True)),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
                ('unit_of_measurement', models.CharField(blank=True, max_length=50, null=True)),
                ('log_interval', models.IntegerField(blank=True, null=True)),
                ('log_interval_time', models.CharField(blank=True, max_length=50, null=True)),
                ('deadband', models.FloatField(blank=True, null=True)),
                ('digits', models.IntegerField(blank=True, null=True)),
                ('value_type', models.IntegerField(blank=True, null=True)),
                ('guid', models.CharField(blank=True, max_length=100, null=True)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='plotly_integration.uspbioreactorunit')),
            ],
            options={
                'db_table': 'usp_parameter_track',
                'ordering': ['track_number'],
            },
        ),
        migrations.CreateModel(
            name='USPBioreactorData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('duration', models.FloatField(blank=True, null=True)),
                ('value', models.FloatField(blank=True, null=True)),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data', to='plotly_integration.uspparametertrack')),
            ],
            options={
                'db_table': 'usp_bioreactor_data',
                'ordering': ['timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='uspparametertrack',
            index=models.Index(fields=['unit', 'parameter_name'], name='usp_paramet_unit_id_0e3749_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='uspparametertrack',
            unique_together={('unit', 'track_number')},
        ),
        migrations.AddIndex(
            model_name='uspbioreactordata',
            index=models.Index(fields=['track', 'timestamp'], name='usp_bioreac_track_i_a6707a_idx'),
        ),
        migrations.AddIndex(
            model_name='uspbioreactordata',
            index=models.Index(fields=['timestamp'], name='usp_bioreac_timesta_2bb4c3_idx'),
        ),
    ]
