# Generated by Django 5.1.4 on 2025-08-28 23:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plotly_integration', '0108_add_usp_dasgip_models'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='USPBioreactorRun',
            fields=[
                ('up_number', models.CharField(help_text='UP Number (Primary Key)', max_length=50, primary_key=True, serialize=False)),
                ('file_name', models.CharField(help_text='Original CSV filename', max_length=255)),
                ('file_path', models.TextField(help_text='Path to uploaded file')),
                ('project_name', models.CharField(blank=True, help_text='DASGIP project name', max_length=255)),
                ('unit_number', models.IntegerField(help_text='DASGIP unit number (1, 3, 4, 7, 8, etc.)')),
                ('setup_name', models.CharField(blank=True, help_text='Setup description', max_length=255)),
                ('start_timestamp', models.DateTimeField(help_text='Run start time')),
                ('stop_timestamp', models.DateTimeField(help_text='Run stop time')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('comment', models.TextField(blank=True, help_text='Run notes/comments')),
                ('host', models.CharField(blank=True, help_text='DASGIP host system', max_length=100)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bioreactor Run',
                'verbose_name_plural': 'Bioreactor Runs',
                'db_table': 'usp_bioreactor_runs',
            },
        ),
        migrations.CreateModel(
            name='USPTimeSeriesData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(help_text='Data timestamp')),
                ('duration', models.FloatField(blank=True, help_text='Duration from start (hours)', null=True)),
                ('do_pv', models.FloatField(blank=True, help_text='DO Process Value (% DO)', null=True)),
                ('do_sp', models.FloatField(blank=True, help_text='DO Setpoint (% DO)', null=True)),
                ('do_out', models.FloatField(blank=True, help_text='DO Controller Output (%)', null=True)),
                ('ph_pv', models.FloatField(blank=True, help_text='pH Process Value', null=True)),
                ('ph_sp', models.FloatField(blank=True, help_text='pH Setpoint', null=True)),
                ('ph_out', models.FloatField(blank=True, help_text='pH Controller Output (%)', null=True)),
                ('temp_pv', models.FloatField(blank=True, help_text='Temperature Process Value (°C)', null=True)),
                ('temp_sp', models.FloatField(blank=True, help_text='Temperature Setpoint (°C)', null=True)),
                ('temp_out', models.FloatField(blank=True, help_text='Temperature Controller Output (%)', null=True)),
                ('rpm_pv', models.FloatField(blank=True, help_text='Agitation Speed Process Value (RPM)', null=True)),
                ('rpm_sp', models.FloatField(blank=True, help_text='Agitation Speed Setpoint (RPM)', null=True)),
                ('volume_pv', models.FloatField(blank=True, help_text='Reactor Volume (mL)', null=True)),
                ('air_flow_pv', models.FloatField(blank=True, help_text='Air Flow Process Value (sL/h)', null=True)),
                ('air_flow_sp', models.FloatField(blank=True, help_text='Air Flow Setpoint (sL/h)', null=True)),
                ('feed_a_pv', models.FloatField(blank=True, help_text='Feed A Flow Process Value (mL/h)', null=True)),
                ('feed_a_sp', models.FloatField(blank=True, help_text='Feed A Flow Setpoint (mL/h)', null=True)),
                ('feed_b_pv', models.FloatField(blank=True, help_text='Feed B Flow Process Value (mL/h)', null=True)),
                ('feed_b_sp', models.FloatField(blank=True, help_text='Feed B Flow Setpoint (mL/h)', null=True)),
                ('o2_conc_pv', models.FloatField(blank=True, help_text='O2 Concentration Process Value (%)', null=True)),
                ('o2_conc_sp', models.FloatField(blank=True, help_text='O2 Concentration Setpoint (%)', null=True)),
                ('co2_conc_pv', models.FloatField(blank=True, help_text='CO2 Concentration Process Value (%)', null=True)),
                ('co2_conc_sp', models.FloatField(blank=True, help_text='CO2 Concentration Setpoint (%)', null=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeseries_data', to='plotly_integration.uspbioreactorrun')),
            ],
            options={
                'verbose_name': 'Time Series Data',
                'verbose_name_plural': 'Time Series Data',
                'db_table': 'usp_timeseries_data',
                'ordering': ['run', 'timestamp'],
                'indexes': [models.Index(fields=['run', 'timestamp'], name='usp_timeser_run_id_b2e526_idx'), models.Index(fields=['timestamp'], name='usp_timeser_timesta_ee3d77_idx')],
            },
        ),
    ]
