# Generated by Django 5.1.4 on 2025-09-02 20:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plotly_integration', '0111_add_usp_sample_sets'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormulationCondition',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('formulation_number', models.IntegerField(help_text='Formulation identifier number')),
                ('buffer_type', models.CharField(blank=True, help_text='Buffer type (e.g., Phosphate, Histidine)', max_length=100, null=True)),
                ('buffer_concentration', models.FloatField(blank=True, help_text='Buffer concentration (mM)', null=True)),
                ('ph', models.FloatField(help_text='pH value')),
                ('arginine_hcl', models.FloatField(blank=True, help_text='Arginine HCl concentration (mg/mL)', null=True)),
                ('sucrose', models.FloatField(blank=True, help_text='Sucrose concentration (mg/mL)', null=True)),
                ('sorbitol', models.FloatField(blank=True, help_text='Sorbitol concentration (mg/mL)', null=True)),
                ('trehalose', models.FloatField(blank=True, help_text='Trehalose concentration (mg/mL)', null=True)),
                ('glycine', models.FloatField(blank=True, help_text='Glycine concentration (mg/mL)', null=True)),
                ('polysorbate_80', models.FloatField(blank=True, help_text='Polysorbate 80 concentration (mg/mL)', null=True)),
                ('excipient_1_name', models.CharField(blank=True, max_length=100, null=True)),
                ('excipient_1_concentration', models.FloatField(blank=True, null=True)),
                ('excipient_2_name', models.CharField(blank=True, max_length=100, null=True)),
                ('excipient_2_concentration', models.FloatField(blank=True, null=True)),
                ('excipient_3_name', models.CharField(blank=True, max_length=100, null=True)),
                ('excipient_3_concentration', models.FloatField(blank=True, null=True)),
                ('osmolality', models.FloatField(blank=True, help_text='Osmolality (mOsm/kg)', null=True)),
            ],
            options={
                'verbose_name': 'Formulation Condition',
                'verbose_name_plural': 'Formulation Conditions',
                'db_table': 'formulation_condition',
            },
        ),
        migrations.CreateModel(
            name='FormulationStudy',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('study_id', models.CharField(help_text='Study identifier (e.g., FD-003)', max_length=50, unique=True)),
                ('name', models.CharField(help_text='Study name or description', max_length=200)),
                ('molecule', models.CharField(help_text='Molecule being tested', max_length=100)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Formulation Study',
                'verbose_name_plural': 'Formulation Studies',
                'db_table': 'formulation_study',
            },
        ),
        migrations.AlterUniqueTogether(
            name='uspbioreactorunit',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='uspbioreactorunit',
            name='experiment',
        ),
        migrations.RemoveField(
            model_name='uspparametertrack',
            name='unit',
        ),
        migrations.RemoveField(
            model_name='uspdasgipexperiment',
            name='file',
        ),
        migrations.RemoveField(
            model_name='uspdasgipfile',
            name='uploaded_by',
        ),
        migrations.AlterUniqueTogether(
            name='uspparametertrack',
            unique_together=None,
        ),
        migrations.AlterField(
            model_name='uspanalysisrequest',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='uspsampleset',
            name='created_by',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='uspsamplesetmembership',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='FormulationSample',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sample_id', models.CharField(help_text='Sample identifier (e.g., FD-003-001)', max_length=50, unique=True)),
                ('storage_condition', models.CharField(choices=[('FT', 'Freeze/Thaw'), ('25C', '25°C'), ('40C', '40°C'), ('4C', '4°C'), ('-80C', '-80°C')], max_length=10)),
                ('pull_day', models.IntegerField(help_text='Day sample was pulled for analysis')),
                ('time_point_months', models.FloatField(help_text='Time point in months')),
                ('appearance', models.CharField(blank=True, max_length=200, null=True)),
                ('concentration', models.FloatField(blank=True, help_text='Protein concentration (mg/mL)', null=True)),
                ('ph_measured', models.FloatField(blank=True, help_text='Measured pH', null=True)),
                ('osmolality_measured', models.FloatField(blank=True, help_text='Measured osmolality (mOsm/kg)', null=True)),
                ('formulation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='samples', to='plotly_integration.formulationcondition')),
            ],
            options={
                'verbose_name': 'Formulation Sample',
                'verbose_name_plural': 'Formulation Samples',
                'db_table': 'formulation_sample',
            },
        ),
        migrations.CreateModel(
            name='FormulationSecResult',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('result_id', models.CharField(blank=True, help_text='External result ID', max_length=100, null=True)),
                ('hmw_percent', models.FloatField(help_text='High Molecular Weight species (%)')),
                ('main_percent', models.FloatField(help_text='Main peak/monomer (%)')),
                ('lmw_percent', models.FloatField(help_text='Low Molecular Weight species (%)')),
                ('total_area', models.FloatField(blank=True, help_text='Total chromatogram area', null=True)),
                ('tm_celsius', models.FloatField(blank=True, help_text='Melting temperature (°C)', null=True)),
                ('scattering_onset', models.FloatField(blank=True, help_text='Light scattering onset temperature', null=True)),
                ('analysis_date', models.DateTimeField(blank=True, null=True)),
                ('instrument', models.CharField(blank=True, max_length=100, null=True)),
                ('method', models.CharField(blank=True, max_length=200, null=True)),
                ('analyst', models.CharField(blank=True, max_length=100, null=True)),
                ('sample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sec_results', to='plotly_integration.formulationsample')),
            ],
            options={
                'verbose_name': 'SEC Result',
                'verbose_name_plural': 'SEC Results',
                'db_table': 'formulation_sec_result',
            },
        ),
        migrations.CreateModel(
            name='FormulationStabilityMetric',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('storage_condition', models.CharField(help_text='Storage condition', max_length=10)),
                ('hmw_rate_per_month', models.FloatField(blank=True, help_text='HMW increase rate (% per month)', null=True)),
                ('main_rate_per_month', models.FloatField(blank=True, help_text='Main decrease rate (% per month)', null=True)),
                ('lmw_rate_per_month', models.FloatField(blank=True, help_text='LMW increase rate (% per month)', null=True)),
                ('r_squared', models.FloatField(blank=True, help_text='R² for linear fit', null=True)),
                ('half_life_months', models.FloatField(blank=True, help_text='Estimated half-life (months)', null=True)),
                ('stability_score', models.FloatField(blank=True, help_text='Overall stability score (0-100)', null=True)),
                ('formulation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stability_metrics', to='plotly_integration.formulationcondition')),
            ],
            options={
                'verbose_name': 'Stability Metric',
                'verbose_name_plural': 'Stability Metrics',
                'db_table': 'formulation_stability_metric',
            },
        ),
        migrations.AddField(
            model_name='formulationcondition',
            name='study',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conditions', to='plotly_integration.formulationstudy'),
        ),
        migrations.DeleteModel(
            name='USPBioreactorData',
        ),
        migrations.DeleteModel(
            name='USPBioreactorUnit',
        ),
        migrations.DeleteModel(
            name='USPParameterTrack',
        ),
        migrations.DeleteModel(
            name='USPDasgipExperiment',
        ),
        migrations.DeleteModel(
            name='USPDasgipFile',
        ),
        migrations.AddIndex(
            model_name='formulationsample',
            index=models.Index(fields=['formulation', 'storage_condition', 'time_point_months'], name='formulation_formula_36640d_idx'),
        ),
        migrations.AddIndex(
            model_name='formulationsample',
            index=models.Index(fields=['storage_condition', 'time_point_months'], name='formulation_storage_71a542_idx'),
        ),
        migrations.AddIndex(
            model_name='formulationsecresult',
            index=models.Index(fields=['sample', 'analysis_date'], name='formulation_sample__45c4b4_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='formulationstabilitymetric',
            unique_together={('formulation', 'storage_condition')},
        ),
        migrations.AlterUniqueTogether(
            name='formulationcondition',
            unique_together={('study', 'formulation_number')},
        ),
    ]
