# Generated by Django 5.1.4 on 2025-09-03 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plotly_integration', '0112_formulationcondition_formulationstudy_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormulationData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sample_number', models.CharField(help_text='Sample identifier (e.g., FD-003-001)', max_length=50, unique=True)),
                ('experiment_id', models.CharField(help_text='Experiment ID extracted from sample number (e.g., FD-003)', max_length=20)),
                ('formulation_number', models.CharField(help_text='Formulation number extracted from sample number (e.g., 001)', max_length=10)),
                ('buffer', models.CharField(blank=True, help_text='Buffer type', max_length=100, null=True)),
                ('ph', models.FloatField(blank=True, help_text='pH value', null=True)),
                ('excipients', models.TextField(blank=True, help_text='Excipients description', null=True)),
                ('formulation', models.TextField(blank=True, help_text='Complete formulation description', null=True)),
                ('condition', models.CharField(blank=True, help_text='Storage condition', max_length=50, null=True)),
                ('pull_day', models.IntegerField(blank=True, help_text='Day sample was pulled', null=True)),
                ('time_point_months', models.FloatField(blank=True, help_text='Time point in months', null=True)),
                ('appearance', models.CharField(blank=True, help_text='Sample appearance', max_length=200, null=True)),
                ('concentration', models.FloatField(blank=True, help_text='Concentration (mg/mL)', null=True)),
                ('measured_ph', models.FloatField(blank=True, help_text='Measured pH at analysis', null=True)),
                ('result_id', models.CharField(blank=True, help_text='Analysis result ID', max_length=100, null=True)),
                ('hmw_percent', models.FloatField(blank=True, help_text='High Molecular Weight species (%)', null=True)),
                ('main_percent', models.FloatField(blank=True, help_text='Main peak (%)', null=True)),
                ('lmw_percent', models.FloatField(blank=True, help_text='Low Molecular Weight species (%)', null=True)),
                ('total_area', models.FloatField(blank=True, help_text='Total chromatogram area', null=True)),
                ('osmolality', models.FloatField(blank=True, help_text='Osmolality (mOsm/kg)', null=True)),
                ('tm_celsius', models.FloatField(blank=True, help_text='Melting temperature (°C)', null=True)),
                ('scattering_onset', models.FloatField(blank=True, help_text='Scattering onset temperature', null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True, help_text='Additional notes', null=True)),
            ],
            options={
                'verbose_name': 'Formulation Data',
                'verbose_name_plural': 'Formulation Data',
                'db_table': 'formulation_data_simple',
                'ordering': ['sample_number', 'time_point_months'],
            },
        ),
    ]
