# Generated by Django 5.1.4 on 2025-09-03 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plotly_integration', '0113_add_formulation_data'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='formulationdata',
            options={'ordering': ['sample_number'], 'verbose_name': 'Formulation Data', 'verbose_name_plural': 'Formulation Data'},
        ),
        migrations.RemoveField(
            model_name='formulationdata',
            name='experiment_id',
        ),
        migrations.RemoveField(
            model_name='formulationdata',
            name='formulation_number',
        ),
        migrations.RemoveField(
            model_name='formulationdata',
            name='hmw_percent',
        ),
        migrations.RemoveField(
            model_name='formulationdata',
            name='lmw_percent',
        ),
        migrations.RemoveField(
            model_name='formulationdata',
            name='main_percent',
        ),
        migrations.RemoveField(
            model_name='formulationdata',
            name='measured_ph',
        ),
        migrations.RemoveField(
            model_name='formulationdata',
            name='notes',
        ),
        migrations.AddField(
            model_name='formulationdata',
            name='hmw',
            field=models.FloatField(blank=True, help_text='HMW', null=True),
        ),
        migrations.AddField(
            model_name='formulationdata',
            name='lmw',
            field=models.FloatField(blank=True, help_text='LMW', null=True),
        ),
        migrations.AddField(
            model_name='formulationdata',
            name='main',
            field=models.FloatField(blank=True, help_text='Main', null=True),
        ),
        migrations.AddField(
            model_name='formulationdata',
            name='ph_measured',
            field=models.FloatField(blank=True, help_text='pH (measured)', null=True),
        ),
        migrations.AlterField(
            model_name='formulationdata',
            name='appearance',
            field=models.CharField(blank=True, help_text='Appearance', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='formulationdata',
            name='buffer',
            field=models.CharField(blank=True, help_text='Buffer', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='formulationdata',
            name='condition',
            field=models.CharField(blank=True, help_text='Condition', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='formulationdata',
            name='excipients',
            field=models.TextField(blank=True, help_text='Excipients', null=True),
        ),
        migrations.AlterField(
            model_name='formulationdata',
            name='formulation',
            field=models.TextField(blank=True, help_text='Formulation', null=True),
        ),
        migrations.AlterField(
            model_name='formulationdata',
            name='ph',
            field=models.FloatField(blank=True, help_text='pH', null=True),
        ),
        migrations.AlterField(
            model_name='formulationdata',
            name='pull_day',
            field=models.IntegerField(blank=True, help_text='Pull Day', null=True),
        ),
        migrations.AlterField(
            model_name='formulationdata',
            name='result_id',
            field=models.CharField(blank=True, help_text='Result ID', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='formulationdata',
            name='sample_number',
            field=models.CharField(help_text='Sample Number', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='formulationdata',
            name='scattering_onset',
            field=models.FloatField(blank=True, help_text='Scattering Onset', null=True),
        ),
        migrations.AlterField(
            model_name='formulationdata',
            name='time_point_months',
            field=models.FloatField(blank=True, help_text='Time Point (months)', null=True),
        ),
        migrations.AlterField(
            model_name='formulationdata',
            name='tm_celsius',
            field=models.FloatField(blank=True, help_text='Tm (°C)', null=True),
        ),
        migrations.AlterField(
            model_name='formulationdata',
            name='total_area',
            field=models.FloatField(blank=True, help_text='Total Area', null=True),
        ),
    ]
