# Generated by Django 5.1.4 on 2025-09-05 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plotly_integration', '0114_update_formulation_data_structure'),
    ]

    operations = [
        migrations.AddField(
            model_name='sartoflowtimeseriesdata',
            name='unit_step',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
