# Generated by Django 5.1.4 on 2025-09-10 19:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plotly_integration', '0115_add_unit_step_to_sartoflow'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FormulationExperiment',
            fields=[
                ('experiment_id', models.CharField(help_text='e.g., FD-003', max_length=50, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(help_text='Experiment name/description', max_length=200)),
                ('molecule', models.CharField(help_text='Molecule/Protein name', max_length=100)),
                ('target_concentration_mg_ml', models.FloatField(default=50.0, help_text='Target protein concentration')),
                ('start_date', models.DateField(blank=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'formulation_experiment',
                'ordering': ['-created_date'],
            },
        ),
        migrations.CreateModel(
            name='FormulationMatrix',
            fields=[
                ('formulation_id', models.AutoField(primary_key=True, serialize=False)),
                ('formulation_number', models.IntegerField(help_text='Formulation number (1, 2, 3...)')),
                ('target_ph', models.FloatField(help_text='Target pH')),
                ('osmolality', models.FloatField(blank=True, help_text='Target osmolality (mOsm/kg)', null=True)),
                ('notes', models.TextField(blank=True)),
                ('experiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formulations', to='plotly_integration.formulationexperiment')),
            ],
            options={
                'db_table': 'formulation_matrix',
                'ordering': ['experiment', 'formulation_number'],
            },
        ),
        migrations.CreateModel(
            name='FormulationComponent',
            fields=[
                ('component_id', models.AutoField(primary_key=True, serialize=False)),
                ('component_type', models.CharField(choices=[('buffer', 'Buffer'), ('excipient', 'Excipient'), ('surfactant', 'Surfactant'), ('salt', 'Salt'), ('sugar', 'Sugar/Polyol'), ('amino_acid', 'Amino Acid'), ('preservative', 'Preservative'), ('other', 'Other')], max_length=20)),
                ('name', models.CharField(help_text='e.g., Histidine, Sucrose, Arginine HCl, PS80', max_length=100)),
                ('concentration', models.FloatField()),
                ('unit', models.CharField(choices=[('mg/mL', 'mg/mL'), ('mM', 'mM'), ('M', 'M'), ('g/L', 'g/L'), ('%', '% (w/v)'), ('% v/v', '% (v/v)')], default='mg/mL', max_length=10)),
                ('formulation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='plotly_integration.formulationmatrix')),
            ],
            options={
                'db_table': 'formulation_component',
                'ordering': ['formulation', 'component_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='FormulationSample',
            fields=[
                ('sample_id', models.CharField(help_text='e.g., FD-003-001', max_length=50, primary_key=True, serialize=False)),
                ('storage_condition', models.CharField(choices=[('FT', 'Freeze/Thaw'), ('25C', '25°C'), ('40C', '40°C'), ('4C', '4°C'), ('-80C', '-80°C')], max_length=10)),
                ('pull_day', models.IntegerField(blank=True, help_text='Day of pull (e.g., 7, 14, 30)', null=True)),
                ('time_point_months', models.FloatField(help_text='Time point in months (e.g., 0, 1, 3, 6, 12)')),
                ('pull_date', models.DateField(blank=True, null=True)),
                ('appearance', models.CharField(blank=True, help_text='Visual appearance', max_length=200)),
                ('concentration_mg_ml', models.FloatField(blank=True, help_text='Measured protein concentration', null=True)),
                ('ph_measured', models.FloatField(blank=True, help_text='Measured pH', null=True)),
                ('osmolality_measured', models.FloatField(blank=True, help_text='Measured osmolality (mOsm/kg)', null=True)),
                ('sec_result_id', models.CharField(blank=True, help_text='HPLC/SEC Result ID', max_length=100)),
                ('hmw', models.FloatField(blank=True, help_text='High Molecular Weight (%)', null=True)),
                ('main', models.FloatField(blank=True, help_text='Main Peak (%)', null=True)),
                ('lmw', models.FloatField(blank=True, help_text='Low Molecular Weight (%)', null=True)),
                ('total_area', models.FloatField(blank=True, help_text='Total peak area', null=True)),
                ('tm_celsius', models.FloatField(blank=True, help_text='Melting temperature (°C)', null=True)),
                ('scattering_onset', models.FloatField(blank=True, help_text='Light scattering onset temperature (°C)', null=True)),
                ('analysis_date', models.DateField(blank=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True)),
                ('analyst', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('formulation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='samples', to='plotly_integration.formulationmatrix')),
            ],
            options={
                'db_table': 'formulation_sample',
                'ordering': ['formulation__experiment', 'formulation__formulation_number', 'time_point_months', 'storage_condition'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='formulationmatrix',
            unique_together={('experiment', 'formulation_number')},
        ),
        migrations.AlterUniqueTogether(
            name='formulationcomponent',
            unique_together={('formulation', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='formulationsample',
            unique_together={('formulation', 'storage_condition', 'time_point_months')},
        ),
    ]
