# Generated by Django 5.1.4 on 2025-09-17 18:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plotly_integration', '0117_alter_formulationsample_sec_result_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CLDAnalytics',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('analysis_type', models.CharField(choices=[('SEC', 'Size Exclusion Chromatography'), ('Titer', 'Titer'), ('Octet', 'Octet'), ('CE-SDS', 'CE-SDS'), ('cIEF', 'cIEF'), ('LCMS', 'LC-MS')], max_length=20)),
                ('required', models.BooleanField(default=True)),
                ('scheduled_date', models.DateField(blank=True, null=True)),
                ('completed_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Complete', 'Complete'), ('Reported', 'Reported')], default='Pending', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'cld_analytics',
                'ordering': ['project', 'scheduled_date', 'analysis_type'],
            },
        ),
        migrations.CreateModel(
            name='CLDProject',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('project_number', models.CharField(max_length=100)),
                ('number_of_samples', models.IntegerField()),
                ('start_date', models.DateField()),
                ('target_harvest_date', models.DateField()),
                ('harvest_type', models.CharField(choices=[('24_deepwell', '24 Deepwell'), ('shake_flask', 'Shake Flask')], max_length=50)),
                ('purification_type', models.CharField(choices=[('PROA', 'Protein A'), ('Kappa', 'Kappa'), ('Lambda', 'Lambda'), ('G_protein', 'G Protein'), ('L_protein', 'L Protein'), ('Other', 'Other')], max_length=50)),
                ('status', models.CharField(choices=[('Planning', 'Planning'), ('In Progress', 'In Progress'), ('Complete', 'Complete')], default='Planning', max_length=20)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'cld_project',
                'ordering': ['-created_date', '-start_date'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='formulationcondition',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='formulationcondition',
            name='study',
        ),
        migrations.RemoveField(
            model_name='formulationstabilitymetric',
            name='formulation',
        ),
        migrations.DeleteModel(
            name='FormulationData',
        ),
        migrations.RemoveField(
            model_name='formulationsecresult',
            name='sample',
        ),
        migrations.AlterUniqueTogether(
            name='formulationstabilitymetric',
            unique_together=None,
        ),
        migrations.AddField(
            model_name='cldanalytics',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='plotly_integration.cldproject'),
        ),
        migrations.DeleteModel(
            name='FormulationStudy',
        ),
        migrations.DeleteModel(
            name='FormulationCondition',
        ),
        migrations.DeleteModel(
            name='FormulationStabilityMetric',
        ),
        migrations.DeleteModel(
            name='FormulationSecResult',
        ),
        migrations.AddIndex(
            model_name='cldproject',
            index=models.Index(fields=['project_number', '-created_date'], name='cld_project_project_96c203_idx'),
        ),
        migrations.AddIndex(
            model_name='cldproject',
            index=models.Index(fields=['status', '-start_date'], name='cld_project_status_7d677a_idx'),
        ),
        migrations.AddIndex(
            model_name='cldanalytics',
            index=models.Index(fields=['project', 'status'], name='cld_analyti_project_1f0570_idx'),
        ),
        migrations.AddIndex(
            model_name='cldanalytics',
            index=models.Index(fields=['scheduled_date', 'status'], name='cld_analyti_schedul_e6e53b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='cldanalytics',
            unique_together={('project', 'analysis_type')},
        ),
    ]
