# Generated by Django 5.1.4 on 2025-09-18 17:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plotly_integration', '0118_add_cld_project_management_models'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cldproject',
            name='options',
            field=models.CharField(choices=[('Minipool', 'Minipool'), ('Bulkpool', 'Bulkpool'), ('Minipool+Bulkpool', 'Minipool+Bulkpool')], default='Minipool', max_length=50),
        ),
        migrations.AddField(
            model_name='cldproject',
            name='project_id',
            field=models.CharField(default='CLD-2025-001', max_length=100),
        ),
        migrations.AddField(
            model_name='cldproject',
            name='sip_number',
            field=models.CharField(default='SIP-001', max_length=100),
        ),
        migrations.AddField(
            model_name='cldproject',
            name='transfection_amount_mg',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='cldproject',
            name='transfection_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cldproject',
            name='transfection_type',
            field=models.CharField(choices=[('Lonza', 'Lonza'), ('BTX', 'BTX')], default='Lonza', max_length=20),
        ),
        migrations.AlterField(
            model_name='cldproject',
            name='harvest_type',
            field=models.CharField(blank=True, choices=[('24_deepwell', '24 Deepwell'), ('48_deepwell', '48 Deepwell'), ('shake_flask', 'Shake Flask'), ('beacon', 'Beacon')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='cldproject',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cldproject',
            name='target_harvest_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='CLDProcessTemplate',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('is_default', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'cld_process_template',
                'ordering': ['-created_date'],
            },
        ),
        migrations.CreateModel(
            name='CLDProcessStep',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('step_name', models.CharField(choices=[('Transfection', 'Transfection'), ('mP/BP', 'mP/BP'), ('Recovery', 'Recovery'), ('Beacon', 'Beacon'), ('Grow Up', 'Grow Up'), ('Cydem', 'Cydem'), ('Harvest', 'Harvest'), ('Purification', 'Purification'), ('Analytics', 'Analytics')], max_length=50)),
                ('step_order', models.PositiveIntegerField()),
                ('planned_duration_days', models.PositiveIntegerField()),
                ('actual_duration_days', models.PositiveIntegerField(blank=True, null=True)),
                ('planned_start_date', models.DateField(blank=True, null=True)),
                ('actual_start_date', models.DateField(blank=True, null=True)),
                ('planned_end_date', models.DateField(blank=True, null=True)),
                ('actual_end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Complete', 'Complete'), ('Skipped', 'Skipped')], default='Pending', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='process_steps', to='plotly_integration.cldproject')),
            ],
            options={
                'db_table': 'cld_process_step',
                'ordering': ['project', 'step_order'],
                'indexes': [models.Index(fields=['project', 'step_order'], name='cld_process_project_0571c2_idx'), models.Index(fields=['status', 'planned_start_date'], name='cld_process_status_44b005_idx')],
                'unique_together': {('project', 'step_name')},
            },
        ),
        migrations.CreateModel(
            name='CLDProcessTemplateStep',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('step_name', models.CharField(choices=[('Transfection', 'Transfection'), ('mP/BP', 'mP/BP'), ('Recovery', 'Recovery'), ('Beacon', 'Beacon'), ('Grow Up', 'Grow Up'), ('Cydem', 'Cydem'), ('Harvest', 'Harvest'), ('Purification', 'Purification'), ('Analytics', 'Analytics')], max_length=50)),
                ('step_order', models.PositiveIntegerField()),
                ('default_duration_days', models.PositiveIntegerField()),
                ('is_required', models.BooleanField(default=True)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='template_steps', to='plotly_integration.cldprocesstemplate')),
            ],
            options={
                'db_table': 'cld_process_template_step',
                'ordering': ['template', 'step_order'],
                'unique_together': {('template', 'step_name')},
            },
        ),
    ]
