# Generated by Django 5.1.4 on 2025-09-23 18:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plotly_integration', '0120_create_usp_experiment_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='USPSeedTrain',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('seed_train_id', models.CharField(max_length=100, unique=True)),
                ('vessel_type', models.CharField(choices=[('T25', 'T25 Flask'), ('T75', 'T75 Flask'), ('T175', 'T175 Flask'), ('T225', 'T225 Flask'), ('125mL_SF', '125mL Shake Flask'), ('250mL_SF', '250mL Shake Flask'), ('500mL_SF', '500mL Shake Flask')], max_length=20)),
                ('thaw_date', models.DateField()),
                ('culture_volume', models.FloatField(help_text='mL')),
                ('cell_line', models.CharField(max_length=100)),
                ('media_type', models.CharField(max_length=100)),
                ('passage_number', models.IntegerField(blank=True, null=True)),
                ('vial_id', models.CharField(blank=True, max_length=100, null=True)),
                ('viability_at_thaw', models.FloatField(blank=True, help_text='percentage', null=True)),
                ('cell_density_at_thaw', models.FloatField(blank=True, help_text='cells/mL', null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'usp_seed_train',
                'ordering': ['process_step', 'seed_train_id'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='uspprocessstep',
            name='unique_experiment_step_order',
        ),
        migrations.RemoveConstraint(
            model_name='uspvessel',
            name='unique_process_step_vessel_id',
        ),
        migrations.AlterField(
            model_name='uspvessel',
            name='vessel_type',
            field=models.CharField(choices=[('2L_BR', '2L Bioreactor'), ('5L_BR', '5L Bioreactor'), ('10L_BR', '10L Bioreactor'), ('50L_BR', '50L Bioreactor'), ('250mL_SF', '250mL Shake Flask'), ('500mL_SF', '500mL Shake Flask'), ('1L_SF', '1L Shake Flask'), ('2L_SF', '2L Shake Flask')], max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='uspprocessstep',
            unique_together={('experiment', 'step_order')},
        ),
        migrations.AlterUniqueTogether(
            name='uspvessel',
            unique_together={('process_step', 'vessel_id')},
        ),
        migrations.AddField(
            model_name='uspseedtrain',
            name='process_step',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seed_trains', to='plotly_integration.uspprocessstep'),
        ),
        migrations.AddField(
            model_name='uspvessel',
            name='seed_train',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='downstream_vessels', to='plotly_integration.uspseedtrain'),
        ),
    ]
