# Generated by Django 5.1.4 on 2025-09-23 22:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plotly_integration', '0121_create_seed_train_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uspvessel',
            name='vessel_type',
            field=models.CharField(choices=[('2L_BRX', '2L Bioreactor'), ('5L_BRX', '5L Bioreactor'), ('10L_BRX', '10L Bioreactor'), ('15L_BRX', '15L Bioreactor'), ('250mL_SF', '250mL Shake Flask'), ('500mL_SF', '500mL Shake Flask'), ('1L_SF', '1L Shake Flask'), ('2L_SF', '2L Shake Flask')], max_length=20),
        ),
        migrations.CreateModel(
            name='USPMediaPrep',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('media_id', models.CharField(max_length=100, unique=True)),
                ('media_name', models.CharField(max_length=200)),
                ('media_type', models.CharField(max_length=100)),
                ('batch_size', models.FloatField(help_text='Total volume in L')),
                ('preparation_date', models.DateField()),
                ('expiration_date', models.DateField(blank=True, null=True)),
                ('prepared_by', models.CharField(max_length=100)),
                ('ph_actual', models.FloatField(blank=True, null=True)),
                ('osmolality_actual', models.FloatField(blank=True, help_text='mOsm/kg', null=True)),
                ('sterility_check', models.BooleanField(default=False)),
                ('storage_location', models.CharField(blank=True, max_length=200, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('experiment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='media_preps', to='plotly_integration.uspexperiment')),
            ],
            options={
                'db_table': 'usp_media_prep',
                'ordering': ['-preparation_date', 'media_id'],
            },
        ),
        migrations.CreateModel(
            name='USPMediaComponent',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('component_type', models.CharField(choices=[('base_powder', 'Base Powder'), ('glucose', 'Glucose'), ('glutamine', 'Glutamine'), ('amino_acid', 'Amino Acid'), ('vitamin', 'Vitamin'), ('salt', 'Salt'), ('growth_factor', 'Growth Factor'), ('antibiotic', 'Antibiotic'), ('buffer', 'Buffer'), ('serum', 'Serum'), ('other', 'Other')], max_length=50)),
                ('component_name', models.CharField(max_length=200)),
                ('lot_number', models.CharField(blank=True, max_length=100, null=True)),
                ('target_amount', models.FloatField()),
                ('actual_amount', models.FloatField()),
                ('unit', models.CharField(choices=[('g', 'g'), ('mg', 'mg'), ('L', 'L'), ('mL', 'mL'), ('µL', 'µL'), ('g/L', 'g/L'), ('mg/L', 'mg/L'), ('mM', 'mM'), ('µM', 'µM'), ('%', '%')], max_length=20)),
                ('vendor', models.CharField(blank=True, max_length=100, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('media_prep', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='plotly_integration.uspmediaprep')),
            ],
            options={
                'db_table': 'usp_media_component',
                'ordering': ['media_prep', 'component_type', 'component_name'],
            },
        ),
    ]
