# Generated by Django 5.1.4 on 2025-09-24 16:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plotly_integration', '0122_alter_uspvessel_vessel_type_uspmediaprep_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='USPMediaRecipe',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('recipe_id', models.CharField(max_length=100, unique=True)),
                ('recipe_name', models.CharField(max_length=200)),
                ('recipe_type', models.CharField(max_length=100)),
                ('version', models.CharField(default='1.0', max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('base_volume', models.FloatField(default=1.0, help_text='Base volume in L for recipe calculations')),
                ('ph_target', models.FloatField(blank=True, null=True)),
                ('osmolality_target', models.FloatField(blank=True, help_text='mOsm/kg', null=True)),
                ('storage_temp', models.CharField(blank=True, max_length=50, null=True)),
                ('shelf_life_days', models.IntegerField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'usp_media_recipe',
                'ordering': ['recipe_type', 'recipe_name'],
            },
        ),
        migrations.AddField(
            model_name='uspmediaprep',
            name='recipe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preparations', to='plotly_integration.uspmediarecipe'),
        ),
        migrations.CreateModel(
            name='USPMediaRecipeComponent',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('component_type', models.CharField(choices=[('base_powder', 'Base Powder'), ('glucose', 'Glucose'), ('glutamine', 'Glutamine'), ('amino_acid', 'Amino Acid'), ('vitamin', 'Vitamin'), ('salt', 'Salt'), ('growth_factor', 'Growth Factor'), ('antibiotic', 'Antibiotic'), ('buffer', 'Buffer'), ('serum', 'Serum'), ('supplement', 'Supplement'), ('other', 'Other')], max_length=50)),
                ('component_name', models.CharField(max_length=200)),
                ('catalog_number', models.CharField(blank=True, max_length=100, null=True)),
                ('concentration_per_liter', models.FloatField(help_text='Amount per liter of final media')),
                ('unit', models.CharField(choices=[('g/L', 'g/L'), ('mg/L', 'mg/L'), ('mL/L', 'mL/L'), ('µL/L', 'µL/L'), ('mM', 'mM'), ('µM', 'µM'), ('%', '%')], max_length=20)),
                ('vendor', models.CharField(blank=True, max_length=100, null=True)),
                ('preparation_notes', models.TextField(blank=True, null=True)),
                ('order_index', models.IntegerField(default=0, help_text='Order for adding components')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_components', to='plotly_integration.uspmediarecipe')),
            ],
            options={
                'db_table': 'usp_media_recipe_component',
                'ordering': ['recipe', 'order_index', 'component_name'],
            },
        ),
    ]
