# Generated by Django 5.1.4 on 2025-09-24 18:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plotly_integration', '0123_uspmediarecipe_uspmediaprep_recipe_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='USPMediaComponentLibrary',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('component_type', models.CharField(choices=[('base_powder', 'Base Powder'), ('glucose', 'Glucose'), ('glutamine', 'Glutamine'), ('amino_acid', 'Amino Acid'), ('vitamin', 'Vitamin'), ('salt', 'Salt'), ('growth_factor', 'Growth Factor'), ('antibiotic', 'Antibiotic'), ('buffer', 'Buffer'), ('serum', 'Serum'), ('supplement', 'Supplement'), ('acid', 'Acid (pH adjustment)'), ('base', 'Base (pH adjustment)'), ('water', 'Water'), ('other', 'Other')], max_length=50)),
                ('component_name', models.CharField(max_length=200)),
                ('catalog_number', models.CharField(blank=True, max_length=100, null=True)),
                ('vendor', models.CharField(blank=True, max_length=100, null=True)),
                ('typical_units', models.CharField(help_text='Typical units used (e.g., g, mL, L)', max_length=50)),
                ('molecular_weight', models.FloatField(blank=True, help_text='g/mol', null=True)),
                ('stock_concentration', models.FloatField(blank=True, null=True)),
                ('stock_concentration_unit', models.CharField(blank=True, max_length=20, null=True)),
                ('storage_conditions', models.CharField(blank=True, max_length=200, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'usp_media_component_library',
                'ordering': ['component_type', 'component_name'],
                'unique_together': {('component_name', 'catalog_number')},
            },
        ),
        migrations.CreateModel(
            name='USPMediaRecipeStep',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('step_number', models.IntegerField(help_text='Order of step in recipe')),
                ('step_type', models.CharField(choices=[('add_component', 'Add Component'), ('add_water', 'Add Water (MilliQ)'), ('stir', 'Stir'), ('heat', 'Heat'), ('cool', 'Cool'), ('measure_ph', 'Measure pH'), ('adjust_ph', 'Adjust pH'), ('measure_osmolality', 'Measure Osmolality'), ('adjust_volume', 'Adjust Volume to Final'), ('filter_sterilize', 'Filter Sterilize'), ('autoclave', 'Autoclave'), ('aliquot', 'Aliquot'), ('note', 'General Note/Instruction')], max_length=50)),
                ('amount_per_liter', models.FloatField(blank=True, help_text='Amount per liter of final volume', null=True)),
                ('amount_unit', models.CharField(blank=True, max_length=20, null=True)),
                ('duration_minutes', models.IntegerField(blank=True, null=True)),
                ('temperature', models.FloatField(blank=True, null=True)),
                ('temperature_unit', models.CharField(default='°C', max_length=10)),
                ('target_ph', models.FloatField(blank=True, null=True)),
                ('target_volume', models.FloatField(blank=True, null=True)),
                ('volume_unit', models.CharField(default='L', max_length=10)),
                ('instructions', models.TextField(blank=True, null=True)),
                ('adjustment_component', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ph_adjustment_steps', to='plotly_integration.uspmediacomponentlibrary')),
                ('component', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recipe_steps', to='plotly_integration.uspmediacomponentlibrary')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='process_steps', to='plotly_integration.uspmediarecipe')),
            ],
            options={
                'db_table': 'usp_media_recipe_step',
                'ordering': ['recipe', 'step_number'],
                'unique_together': {('recipe', 'step_number')},
            },
        ),
    ]
