# Generated by Django 5.1.4 on 2025-09-30 20:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plotly_integration', '0124_uspmediacomponentlibrary_uspmediarecipestep'),
    ]

    operations = [
        migrations.CreateModel(
            name='USPMediaRecipeStepParameter',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('parameter_key', models.CharField(help_text="Parameter name (e.g., 'component_id', 'amount_per_liter')", max_length=50)),
                ('parameter_type', models.CharField(choices=[('integer', 'Integer'), ('float', 'Float'), ('string', 'String'), ('boolean', 'Boolean'), ('fk_component', 'Foreign Key: Component')], help_text='Data type for validation', max_length=20)),
                ('value_text', models.TextField(help_text='String representation of value')),
                ('value_int', models.IntegerField(blank=True, db_index=True, null=True)),
                ('value_float', models.FloatField(blank=True, db_index=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'usp_media_recipe_step_parameter',
            },
        ),
        migrations.RemoveField(
            model_name='uspmediarecipecomponent',
            name='recipe',
        ),
        migrations.AddField(
            model_name='uspmediarecipestep',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='uspmediarecipestep',
            name='instructions',
            field=models.TextField(blank=True, help_text='General instructions or notes', null=True),
        ),
        migrations.AlterField(
            model_name='uspmediarecipestep',
            name='step_type',
            field=models.CharField(choices=[('add_component', 'Add Component'), ('initial_water_fill', 'Initial MilliQ Water Fill (80%)'), ('add_water', 'Add Water (MilliQ)'), ('final_water_fill', 'Final Water Fill (to 100%)'), ('stir', 'Stir'), ('heat', 'Heat'), ('cool', 'Cool'), ('measure_ph', 'Measure pH'), ('adjust_ph', 'Adjust pH'), ('measure_osmolality', 'Measure Osmolality'), ('adjust_osmolality', 'Adjust Osmolality'), ('filter_sterilize', 'Filter Sterilize'), ('autoclave', 'Autoclave'), ('aliquot', 'Aliquot'), ('note', 'General Note/Instruction')], max_length=50),
        ),
        migrations.AddIndex(
            model_name='uspmediarecipestep',
            index=models.Index(fields=['recipe', 'step_type'], name='usp_media_r_recipe__b21301_idx'),
        ),
        migrations.AddIndex(
            model_name='uspmediarecipestep',
            index=models.Index(fields=['step_type', 'step_number'], name='usp_media_r_step_ty_98d8c5_idx'),
        ),
        migrations.AddField(
            model_name='uspmediarecipestepparameter',
            name='step',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameters', to='plotly_integration.uspmediarecipestep'),
        ),
        migrations.DeleteModel(
            name='USPMediaRecipeComponent',
        ),
        migrations.AddIndex(
            model_name='uspmediarecipestepparameter',
            index=models.Index(fields=['step', 'parameter_key'], name='usp_media_r_step_id_b03b0a_idx'),
        ),
        migrations.AddIndex(
            model_name='uspmediarecipestepparameter',
            index=models.Index(fields=['parameter_key', 'value_text'], name='usp_media_r_paramet_100e24_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='uspmediarecipestepparameter',
            unique_together={('step', 'parameter_key')},
        ),
    ]
