# Generated by Django 5.1.4 on 2025-09-30 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plotly_integration', '0125_uspmediarecipestepparameter_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='uspmediarecipestepparameter',
            name='usp_media_r_paramet_100e24_idx',
        ),
    ]
