# Generated by Django 5.1.4 on 2025-09-30 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plotly_integration', '0126_remove_uspmediarecipestepparameter_usp_media_r_paramet_100e24_idx'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uspmediarecipestep',
            name='adjustment_component',
        ),
        migrations.RemoveField(
            model_name='uspmediarecipestep',
            name='amount_per_liter',
        ),
        migrations.RemoveField(
            model_name='uspmediarecipestep',
            name='amount_unit',
        ),
        migrations.RemoveField(
            model_name='uspmediarecipestep',
            name='component',
        ),
        migrations.RemoveField(
            model_name='uspmediarecipestep',
            name='duration_minutes',
        ),
        migrations.RemoveField(
            model_name='uspmediarecipestep',
            name='target_ph',
        ),
        migrations.RemoveField(
            model_name='uspmediarecipestep',
            name='target_volume',
        ),
        migrations.RemoveField(
            model_name='uspmediarecipestep',
            name='temperature',
        ),
        migrations.RemoveField(
            model_name='uspmediarecipestep',
            name='temperature_unit',
        ),
        migrations.RemoveField(
            model_name='uspmediarecipestep',
            name='volume_unit',
        ),
    ]
