# Generated by Django 5.1.4 on 2025-09-30 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plotly_integration', '0127_remove_deprecated_recipe_step_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='uspmediaprep',
            name='date_used_up',
            field=models.DateField(blank=True, help_text='Date when media was used up or discarded', null=True),
        ),
        migrations.AddField(
            model_name='uspmediaprep',
            name='is_used_up',
            field=models.BooleanField(default=False, help_text='Has this media been completely used or discarded?'),
        ),
    ]
