# Generated by Django 5.1.4 on 2025-10-03 17:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plotly_integration', '0131_add_project_id_to_usp_experiment'),
    ]

    operations = [
        migrations.AddField(
            model_name='uspseedtrain',
            name='media_prep',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seed_trains_used', to='plotly_integration.uspmediaprep'),
        ),
        migrations.AddField(
            model_name='uspvessel',
            name='media_prep',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vessels_used', to='plotly_integration.uspmediaprep'),
        ),
    ]
