# Generated by Django 5.1.4 on 2025-10-06 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plotly_integration', '0132_add_media_prep_fk_to_seed_trains_and_vessels'),
    ]

    operations = [
        migrations.AddField(
            model_name='novaflex2',
            name='dilution_factor',
            field=models.FloatField(blank=True, default=1.0, null=True),
        ),
        migrations.AddField(
            model_name='uspvessel',
            name='serial_numbers',
            field=models.JSONField(blank=True, help_text='JSON field for storing vessel serial numbers (DO probes, pH probes, etc.)', null=True),
        ),
    ]
