# Generated by Django 5.1.4 on 2025-10-06 17:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plotly_integration', '0133_add_serial_numbers_and_dilution_factor'),
    ]

    operations = [
        migrations.CreateModel(
            name='USPCellBank',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cell_bank_id', models.CharField(max_length=100, unique=True)),
                ('density', models.FloatField(help_text='Viable cells/mL')),
                ('number_of_vials', models.IntegerField()),
                ('media', models.CharField(help_text='e.g., CHO MaxX + 10% DMSO', max_length=200)),
                ('banking_date', models.DateField()),
                ('bank_age_days', models.IntegerField(blank=True, help_text='Age in days', null=True)),
                ('bank_age_notes', models.TextField(blank=True, null=True)),
                ('ln2_location', models.CharField(blank=True, help_text='Liquid nitrogen storage location', max_length=200, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('seed_train_source', models.ForeignKey(help_text='Seed train from which this cell bank was created', on_delete=django.db.models.deletion.CASCADE, related_name='cell_banks', to='plotly_integration.uspseedtrain')),
            ],
            options={
                'db_table': 'usp_cell_bank',
                'ordering': ['-banking_date', 'cell_bank_id'],
            },
        ),
    ]
