# Generated by Django 5.1.4 on 2025-10-14 04:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plotly_integration', '0134_add_cell_bank_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='OctetExperiment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_id', models.CharField(help_text='UUID from manifest', max_length=100, unique=True)),
                ('experiment_name', models.CharField(db_index=True, max_length=255)),
                ('experiment_type', models.CharField(db_index=True, help_text='KINETICS, QUANTITATION, SCREENING, EPITOPE', max_length=50)),
                ('experiment_subtype', models.CharField(blank=True, help_text='KBASIC, EPITOPE, etc.', max_length=50)),
                ('description', models.TextField(blank=True)),
                ('experiment_datetime', models.CharField(blank=True, help_text='From ExpMethod', max_length=50)),
                ('start_datetime', models.DateTimeField(blank=True, help_text='From FRD files', null=True)),
                ('machine_name', models.CharField(blank=True, max_length=100)),
                ('instrument_type', models.CharField(blank=True, max_length=50)),
                ('instrument_serial', models.CharField(blank=True, max_length=50)),
                ('sensor_type', models.CharField(blank=True, max_length=100)),
                ('temperature', models.FloatField(blank=True, help_text='°C', null=True)),
                ('cycle_time_ms', models.IntegerField(blank=True, null=True)),
                ('flow_rate_units', models.CharField(default='RPM', max_length=20)),
                ('concentration_units', models.CharField(default='µg/ml', max_length=20)),
                ('molar_conc_units', models.CharField(default='nM', max_length=20)),
                ('user_name', models.CharField(blank=True, db_index=True, max_length=100)),
                ('method_template', models.CharField(blank=True, max_length=500)),
                ('consolidated_file_path', models.CharField(help_text='Path to consolidated Excel', max_length=500)),
                ('original_folder_path', models.CharField(blank=True, help_text='Original data folder', max_length=500)),
                ('date_imported', models.DateTimeField(auto_now_add=True)),
                ('imported_by', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'db_table': 'octet_experiment',
                'ordering': ['-start_datetime'],
                'indexes': [models.Index(fields=['run_id'], name='octet_exper_run_id_e71edd_idx'), models.Index(fields=['experiment_name'], name='octet_exper_experim_2daaa9_idx'), models.Index(fields=['experiment_type', 'experiment_subtype'], name='octet_exper_experim_b99031_idx'), models.Index(fields=['start_datetime'], name='octet_exper_start_d_07365b_idx'), models.Index(fields=['user_name'], name='octet_exper_user_na_a427ee_idx')],
            },
        ),
        migrations.CreateModel(
            name='OctetSensorData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor_location', models.CharField(help_text='A1, B1, etc.', max_length=10)),
                ('sensor_type', models.CharField(blank=True, max_length=100)),
                ('sample_id', models.CharField(blank=True, db_index=True, max_length=255)),
                ('loading_sample_id', models.CharField(blank=True, max_length=255)),
                ('baseline_location', models.CharField(blank=True, max_length=10)),
                ('loading_location', models.CharField(blank=True, max_length=10)),
                ('association_location', models.CharField(blank=True, max_length=10)),
                ('concentration', models.FloatField(blank=True, null=True)),
                ('concentration_units', models.CharField(blank=True, max_length=20)),
                ('response', models.FloatField(blank=True, help_text='Binding response (nm)', null=True)),
                ('selected', models.CharField(default='x', max_length=5)),
                ('include', models.CharField(default='x', max_length=5)),
                ('cycle', models.IntegerField(default=1)),
                ('experiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensors', to='plotly_integration.octetexperiment')),
            ],
            options={
                'db_table': 'octet_sensor_data',
                'ordering': ['sensor_location'],
            },
        ),
        migrations.CreateModel(
            name='OctetKineticAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analysis_method', models.CharField(choices=[('1_TO_1_BINDING', '1:1 Binding'), ('2_TO_1_BINDING', '2:1 Heterogeneous Ligand'), ('STEADY_STATE', 'Steady-State Analysis'), ('MASS_TRANSPORT', 'Mass Transport Limitation'), ('CUSTOM', 'Custom Model')], default='1_TO_1_BINDING', max_length=100)),
                ('analysis_date', models.DateTimeField(auto_now_add=True)),
                ('analyzed_by', models.CharField(blank=True, max_length=100)),
                ('KD', models.FloatField(blank=True, help_text='Dissociation constant (M)', null=True)),
                ('kon', models.FloatField(blank=True, help_text='Association rate (1/Ms)', null=True)),
                ('koff', models.FloatField(blank=True, help_text='Dissociation rate (1/s)', null=True)),
                ('Rmax', models.FloatField(blank=True, help_text='Maximum response (nm)', null=True)),
                ('kobs', models.FloatField(blank=True, help_text='Observed rate (1/s)', null=True)),
                ('Req', models.FloatField(blank=True, help_text='Equilibrium response (nm)', null=True)),
                ('chi_squared', models.FloatField(blank=True, null=True)),
                ('R_squared_assoc', models.FloatField(blank=True, null=True)),
                ('R_squared_dissoc', models.FloatField(blank=True, null=True)),
                ('SSG_KD', models.FloatField(blank=True, null=True)),
                ('SSG_Rmax', models.FloatField(blank=True, null=True)),
                ('SSG_R_squared', models.FloatField(blank=True, null=True)),
                ('fit_converged', models.BooleanField(default=False)),
                ('fit_error_message', models.TextField(blank=True)),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kinetic_analyses', to='plotly_integration.octetsensordata')),
            ],
            options={
                'db_table': 'octet_kinetic_analysis',
                'ordering': ['-analysis_date'],
            },
        ),
        migrations.CreateModel(
            name='OctetSensorLayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor_location', models.CharField(max_length=10)),
                ('sensor_state', models.IntegerField(help_text='0=unused, 1=active')),
                ('sensor_type', models.CharField(blank=True, max_length=100)),
                ('sensor_lot', models.CharField(blank=True, max_length=100)),
                ('sensor_info', models.TextField(blank=True)),
                ('experiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensor_layout', to='plotly_integration.octetexperiment')),
            ],
            options={
                'db_table': 'octet_sensor_layout',
            },
        ),
        migrations.CreateModel(
            name='OctetStepData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_number', models.IntegerField()),
                ('step_name', models.CharField(db_index=True, max_length=100)),
                ('step_type', models.CharField(max_length=50)),
                ('step_status', models.CharField(default='OK', max_length=20)),
                ('sample_location', models.CharField(max_length=10)),
                ('sample_id', models.CharField(blank=True, max_length=255)),
                ('sample_group', models.CharField(blank=True, max_length=100)),
                ('sample_row', models.CharField(blank=True, max_length=5)),
                ('well_type', models.CharField(blank=True, max_length=50)),
                ('concentration', models.CharField(blank=True, max_length=50)),
                ('concentration_units', models.CharField(blank=True, max_length=20)),
                ('start_time', models.FloatField(blank=True, help_text='Start time (s)', null=True)),
                ('assay_time', models.FloatField(blank=True, help_text='Duration (s)', null=True)),
                ('actual_time', models.FloatField(blank=True, help_text='Actual duration (s)', null=True)),
                ('temperature', models.FloatField(blank=True, help_text='°C', null=True)),
                ('flow_rate', models.IntegerField(blank=True, help_text='RPM', null=True)),
                ('data_points', models.IntegerField(blank=True, null=True)),
                ('mean_response', models.FloatField(blank=True, help_text='nm', null=True)),
                ('final_response', models.FloatField(blank=True, help_text='nm', null=True)),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='plotly_integration.octetsensordata')),
            ],
            options={
                'db_table': 'octet_step_data',
                'ordering': ['sensor', 'step_number'],
            },
        ),
        migrations.CreateModel(
            name='OctetStepSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_name', models.CharField(max_length=100)),
                ('step_order', models.IntegerField(help_text='Order in sequence')),
                ('assay_time', models.FloatField(help_text='Duration in seconds')),
                ('flow_rate', models.IntegerField(help_text='RPM')),
                ('step_type', models.IntegerField(help_text='Numeric step type code')),
                ('experiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='step_sequence', to='plotly_integration.octetexperiment')),
            ],
            options={
                'db_table': 'octet_step_sequence',
                'ordering': ['experiment', 'step_order'],
            },
        ),
        migrations.CreateModel(
            name='OctetTimeSeriesData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.FloatField(help_text='Time in seconds')),
                ('response', models.FloatField(help_text='Response in nm')),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_series', to='plotly_integration.octetstepdata')),
            ],
            options={
                'db_table': 'octet_time_series_data',
                'ordering': ['step', 'time'],
            },
        ),
        migrations.CreateModel(
            name='OctetSampleLayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_location', models.CharField(max_length=10)),
                ('sample_type', models.CharField(help_text='BUFFER, SAMPLE, KLOAD, etc.', max_length=50)),
                ('sample_state', models.IntegerField(help_text='0=unused, 2=active')),
                ('sample_id', models.CharField(blank=True, max_length=255)),
                ('sample_group', models.CharField(blank=True, max_length=100)),
                ('sample_conc', models.FloatField(blank=True, null=True)),
                ('sample_info', models.TextField(blank=True)),
                ('experiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sample_layout', to='plotly_integration.octetexperiment')),
            ],
            options={
                'db_table': 'octet_sample_layout',
                'indexes': [models.Index(fields=['experiment', 'sample_location'], name='octet_sampl_experim_1c7d7c_idx'), models.Index(fields=['sample_id'], name='octet_sampl_sample__284403_idx')],
                'unique_together': {('experiment', 'sample_location')},
            },
        ),
        migrations.AddIndex(
            model_name='octetsensordata',
            index=models.Index(fields=['experiment', 'sensor_location'], name='octet_senso_experim_060eff_idx'),
        ),
        migrations.AddIndex(
            model_name='octetsensordata',
            index=models.Index(fields=['sample_id'], name='octet_senso_sample__5cdb67_idx'),
        ),
        migrations.AddIndex(
            model_name='octetsensordata',
            index=models.Index(fields=['loading_sample_id'], name='octet_senso_loading_f4672f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='octetsensordata',
            unique_together={('experiment', 'sensor_location', 'cycle')},
        ),
        migrations.AddIndex(
            model_name='octetkineticanalysis',
            index=models.Index(fields=['sensor'], name='octet_kinet_sensor__11fdee_idx'),
        ),
        migrations.AddIndex(
            model_name='octetkineticanalysis',
            index=models.Index(fields=['analysis_method'], name='octet_kinet_analysi_5e53f8_idx'),
        ),
        migrations.AddIndex(
            model_name='octetsensorlayout',
            index=models.Index(fields=['experiment', 'sensor_location'], name='octet_senso_experim_7af677_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='octetsensorlayout',
            unique_together={('experiment', 'sensor_location')},
        ),
        migrations.AddIndex(
            model_name='octetstepdata',
            index=models.Index(fields=['sensor', 'step_number'], name='octet_step__sensor__16cd4d_idx'),
        ),
        migrations.AddIndex(
            model_name='octetstepdata',
            index=models.Index(fields=['step_name'], name='octet_step__step_na_9fb8c3_idx'),
        ),
        migrations.AddIndex(
            model_name='octetstepdata',
            index=models.Index(fields=['step_type'], name='octet_step__step_ty_7be9ee_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='octetstepdata',
            unique_together={('sensor', 'step_number')},
        ),
        migrations.AddIndex(
            model_name='octetstepsequence',
            index=models.Index(fields=['experiment', 'step_order'], name='octet_step__experim_50581f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='octetstepsequence',
            unique_together={('experiment', 'step_order')},
        ),
        migrations.AddIndex(
            model_name='octettimeseriesdata',
            index=models.Index(fields=['step', 'time'], name='octet_time__step_id_befbaf_idx'),
        ),
    ]
