# Generated by Django 5.1.4 on 2025-10-14 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plotly_integration', '0135_octetexperiment_octetsensordata_octetkineticanalysis_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='octetexperiment',
            name='assay_type',
            field=models.CharField(blank=True, choices=[('Asymmetric', 'Asymmetric'), ('Binding Kinetics', 'Binding Kinetics'), ('HCP', 'HCP'), ('Octet Titer', 'Octet Titer')], db_index=True, help_text='Specific assay type', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='octetexperiment',
            name='group',
            field=models.CharField(blank=True, choices=[('PD', 'Process Development'), ('PE', 'Protein Engineering'), ('CLD', 'Cell Science'), ('IO', 'IO')], db_index=True, help_text='Department/group that generated the data', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='octetexperiment',
            name='import_status',
            field=models.CharField(choices=[('pending', 'Pending Import'), ('imported', 'Imported'), ('archived', 'Archived')], db_index=True, default='imported', help_text='Import workflow status', max_length=20),
        ),
        migrations.AddField(
            model_name='octetexperiment',
            name='imported_folder',
            field=models.CharField(blank=True, help_text='Folder path in Imported directory (after import)', max_length=500),
        ),
        migrations.AddField(
            model_name='octetexperiment',
            name='source_folder',
            field=models.CharField(blank=True, help_text='Original folder path in Imports directory', max_length=500),
        ),
    ]
