# Generated by Django 5.1.4 on 2025-10-15 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plotly_integration', '0137_add_timeseries_denormalized_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='OctetAnalysisTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_name', models.CharField(help_text='Unique name for this template', max_length=200, unique=True)),
                ('analysis_type', models.CharField(choices=[('ASYMMETRIC', 'Asymmetric Analysis'), ('KINETICS_1TO1', '1:1 Binding Kinetics'), ('KINETICS_2TO1', '2:1 Binding Kinetics'), ('STEADY_STATE', 'Steady-State Analysis'), ('TITER', 'Titer Quantification'), ('HCP', 'HCP Quantification')], db_index=True, help_text='Type of analysis this template is for', max_length=50)),
                ('description', models.TextField(blank=True, help_text='Optional description of what this template does')),
                ('created_by', models.CharField(blank=True, help_text='Username of template creator', max_length=100)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('is_default', models.BooleanField(default=False, help_text='Whether this is the default template for this analysis type')),
                ('parameters', models.JSONField(help_text='Analysis-specific parameters stored as JSON dictionary')),
            ],
            options={
                'db_table': 'octet_analysis_template',
                'ordering': ['analysis_type', '-is_default', 'template_name'],
                'indexes': [models.Index(fields=['analysis_type'], name='octet_analy_analysi_113fe8_idx'), models.Index(fields=['analysis_type', 'is_default'], name='octet_analy_analysi_7eb9c0_idx'), models.Index(fields=['template_name'], name='octet_analy_templat_a367a0_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('analysis_type',), name='unique_default_per_type')],
            },
        ),
    ]
