# Generated by Django 5.1.4 on 2025-10-15 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plotly_integration', '0138_add_octet_analysis_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='octetexperiment',
            name='vendor_analysis_settings',
            field=models.JSONField(blank=True, help_text='Vendor software analysis settings from HTSettings.efrd (preprocessing, reference wells, etc.)', null=True),
        ),
    ]
