# Generated by Django 5.1.4 on 2025-10-21 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plotly_integration', '0140_add_octet_kinetics_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='octetkineticssensor',
            name='ka_error',
            field=models.FloatField(blank=True, help_text='ka error (1/Ms)', null=True),
        ),
        migrations.AddField(
            model_name='octetkineticssensor',
            name='kd_error',
            field=models.FloatField(blank=True, help_text='KD error (M)', null=True),
        ),
        migrations.AddField(
            model_name='octetkineticssensor',
            name='kdis_error',
            field=models.FloatField(blank=True, help_text='kdis error (1/s)', null=True),
        ),
        migrations.AddField(
            model_name='octetkineticssensor',
            name='kobs',
            field=models.FloatField(blank=True, help_text='Observed rate (1/s)', null=True),
        ),
        migrations.AddField(
            model_name='octetkineticssensor',
            name='kobs_error',
            field=models.FloatField(blank=True, help_text='kobs error (1/s)', null=True),
        ),
        migrations.AddField(
            model_name='octetkineticssensor',
            name='req',
            field=models.FloatField(blank=True, help_text='Equilibrium response (nm)', null=True),
        ),
        migrations.AddField(
            model_name='octetkineticssensor',
            name='req_rmax_percent',
            field=models.FloatField(blank=True, help_text='Req/Rmax (%)', null=True),
        ),
        migrations.AddField(
            model_name='octetkineticssensor',
            name='response',
            field=models.FloatField(blank=True, help_text='Response (nm)', null=True),
        ),
        migrations.AddField(
            model_name='octetkineticssensor',
            name='rmax_error',
            field=models.FloatField(blank=True, help_text='Rmax error (nm)', null=True),
        ),
        migrations.AddField(
            model_name='octetkineticssensor',
            name='rss',
            field=models.FloatField(blank=True, help_text='Residual sum of squares', null=True),
        ),
        migrations.AddField(
            model_name='octetkineticssensor',
            name='ssg_kd',
            field=models.FloatField(blank=True, help_text='Steady-state global KD', null=True),
        ),
        migrations.AddField(
            model_name='octetkineticssensor',
            name='ssg_r_squared',
            field=models.FloatField(blank=True, help_text='Steady-state global R²', null=True),
        ),
        migrations.AddField(
            model_name='octetkineticssensor',
            name='ssg_rmax',
            field=models.FloatField(blank=True, help_text='Steady-state global Rmax', null=True),
        ),
        migrations.AlterField(
            model_name='octetkineticssensor',
            name='r_squared',
            field=models.FloatField(blank=True, help_text='Full R² (goodness of fit)', null=True),
        ),
    ]
