# Generated by Django 5.1.4 on 2025-10-28 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plotly_integration', '0141_add_extended_kinetic_parameters'),
    ]

    operations = [
        migrations.AddField(
            model_name='limsdnassignment',
            name='input_concentration',
            field=models.FloatField(blank=True, help_text='Input concentration in mg/mL', null=True),
        ),
        migrations.AddField(
            model_name='limsdnassignment',
            name='input_volume',
            field=models.FloatField(blank=True, help_text='Input volume in mL', null=True),
        ),
        migrations.AddField(
            model_name='limsdnassignment',
            name='output_concentration',
            field=models.FloatField(blank=True, help_text='Output concentration in mg/mL', null=True),
        ),
        migrations.AddField(
            model_name='limsdnassignment',
            name='output_volume',
            field=models.FloatField(blank=True, help_text='Output volume in mL', null=True),
        ),
    ]
