# Generated by Django 5.1.4 on 2025-10-28 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plotly_integration', '0142_add_mass_balance_to_dn'),
    ]

    operations = [
        migrations.AddField(
            model_name='uspseedtrain',
            name='project_id',
            field=models.CharField(blank=True, help_text='Project identifier', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='uspvessel',
            name='project_id',
            field=models.CharField(blank=True, help_text='Project identifier', max_length=100, null=True),
        ),
    ]
