# Generated by Django 5.1.4 on 2025-10-29 18:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plotly_integration', '0143_uspseedtrain_project_id_uspvessel_project_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='limsdnassignment',
            name='input_pd_sample',
            field=models.ForeignKey(blank=True, help_text='Input PD sample for this DN experiment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dn_as_input', to='plotly_integration.limssampleanalysis'),
        ),
        migrations.AddField(
            model_name='limsdnassignment',
            name='output_pd_sample',
            field=models.ForeignKey(blank=True, help_text='Output PD sample for this DN experiment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dn_as_output', to='plotly_integration.limssampleanalysis'),
        ),
    ]
