# Generated by Django 5.1.4 on 2025-10-31 21:44

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plotly_integration', '0144_add_pd_samples_to_dn'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('molecule_id', models.CharField(db_index=True, help_text='Unique molecule identifier (e.g., SI-212E18)', max_length=50, unique=True)),
                ('priority_set', models.IntegerField(default=1, help_text='Priority grouping (1=highest priority)')),
                ('status', models.CharField(choices=[('Active', 'Active'), ('On Hold', 'On Hold'), ('Cancelled', 'Cancelled'), ('Completed', 'Completed')], db_index=True, default='Active', max_length=20)),
                ('creation_date', models.DateField(blank=True, help_text='Date molecule was created', null=True)),
                ('cloning_finish_date', models.DateField(blank=True, help_text='Date cloning was completed', null=True)),
                ('purification_finish_date', models.DateField(blank=True, help_text='Date purification was completed', null=True)),
                ('lead_time', models.IntegerField(blank=True, help_text='Total lead time in days', null=True)),
                ('notes', models.TextField(blank=True, help_text='Project notes and comments')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, help_text='User assigned to this project', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects_assigned', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this project', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'project_management_project',
                'ordering': ['-priority_set', '-creation_date'],
            },
        ),
        migrations.CreateModel(
            name='ProjectMetrics',
            fields=[
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='metrics', serialize=False, to='plotly_integration.project')),
                ('on_time_score', models.FloatField(default=0, help_text='Score based on timeline adherence')),
                ('priority_score', models.FloatField(default=0, help_text='Score based on priority set')),
                ('resource_score', models.FloatField(default=0, help_text='Score based on resource utilization')),
                ('completion_score', models.FloatField(default=0, help_text='Score based on progress completion')),
                ('weighted_total', models.FloatField(default=0, help_text='Weighted sum of all scores')),
                ('recommendation', models.CharField(choices=[('PUSH FORWARD', 'Push Forward - Continue with high priority'), ('MONITOR', 'Monitor - Track progress, no immediate action'), ('REVIEW', 'Review - Requires management review'), ('CONSIDER CANCELLATION', 'Consider Cancellation - May need to cancel')], default='MONITOR', max_length=50)),
                ('recommendation_reason', models.TextField(blank=True, help_text='Explanation of why this recommendation was made')),
                ('last_calculated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Project Metrics',
                'db_table': 'project_management_metrics',
            },
        ),
        migrations.CreateModel(
            name='ProjectDecisionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('decision_type', models.CharField(choices=[('Status Change', 'Status Change'), ('Priority Change', 'Priority Change'), ('Assignment Change', 'Assignment Change'), ('Push Forward', 'Push Forward'), ('Hold', 'Hold'), ('Cancel', 'Cancel'), ('Reactivate', 'Reactivate')], max_length=50)),
                ('previous_status', models.CharField(blank=True, max_length=20)),
                ('new_status', models.CharField(blank=True, max_length=20)),
                ('rationale', models.TextField(help_text='Reason for this decision')),
                ('system_recommendation', models.CharField(blank=True, help_text='What the system recommended at decision time', max_length=50)),
                ('decision_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decisions_made', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decision_history', to='plotly_integration.project')),
            ],
            options={
                'db_table': 'project_management_decision_history',
                'ordering': ['-decision_date'],
            },
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['status', 'priority_set'], name='project_man_status_929fd6_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['assigned_to', 'status'], name='project_man_assigne_bdf7c7_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['-creation_date'], name='project_man_creatio_cc4cfb_idx'),
        ),
        migrations.AddIndex(
            model_name='projectdecisionhistory',
            index=models.Index(fields=['project', '-decision_date'], name='project_man_project_c3f757_idx'),
        ),
        migrations.AddIndex(
            model_name='projectdecisionhistory',
            index=models.Index(fields=['decision_type'], name='project_man_decisio_f76fba_idx'),
        ),
    ]
