# Generated by Django 5.1.4 on 2025-11-01 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plotly_integration', '0145_add_project_management_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageArrangementSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('set_name', models.CharField(help_text='Unique name for this configuration set', max_length=255, unique=True)),
                ('description', models.TextField(blank=True, help_text='Optional description of this configuration')),
                ('configuration_data', models.JSONField(help_text='JSON array of table rows with molecule_id, phase, project_id, group, subset, notes')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(blank=True, max_length=100)),
                ('layout_mode', models.CharField(choices=[('standard', 'Standard Layout'), ('alternative', 'Alternative Comparison')], default='alternative', help_text='Layout mode used for this configuration', max_length=20)),
            ],
            options={
                'db_table': 'image_arrangement_set',
                'ordering': ['-created_date'],
                'indexes': [models.Index(fields=['set_name'], name='image_arran_set_nam_6cfc41_idx'), models.Index(fields=['-created_date'], name='image_arran_created_98303c_idx')],
            },
        ),
    ]
