# Generated by Django 5.1.4 on 2025-11-05 07:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plotly_integration', '0146_add_image_arrangement_set'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='current_concentration',
            field=models.FloatField(blank=True, help_text='Current stock concentration (mg/mL)', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='current_volume',
            field=models.FloatField(blank=True, help_text='Current stock volume (mL)', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='last_updated_by',
            field=models.ForeignKey(blank=True, help_text='User who last updated stock levels', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='volume_updates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='project',
            name='last_volume_update',
            field=models.DateTimeField(blank=True, help_text='When stock levels were last updated', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='stock_location',
            field=models.CharField(blank=True, help_text='Physical storage location (e.g., Freezer A, Shelf 3)', max_length=100),
        ),
    ]
