# Generated by Django 5.1.4 on 2025-06-24 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plotly_integration', '0101_aktachromatogram_idx_chrom_result_ml_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timeseriesdata',
            options={'managed': True, 'ordering': ['result_id', 'time']},
        ),
        migrations.AddIndex(
            model_name='limsprojectinformation',
            index=models.Index(fields=['protein'], name='lims_projec_protein_94f1af_idx'),
        ),
        migrations.AddIndex(
            model_name='limssampleanalysis',
            index=models.Index(fields=['sample_id'], name='lims_sample_sample__c9d400_idx'),
        ),
        migrations.AddIndex(
            model_name='peakresults',
            index=models.Index(fields=['result_id'], name='peak_result_result__5323fe_idx'),
        ),
        migrations.AddIndex(
            model_name='peakresults',
            index=models.Index(fields=['result_id', 'peak_retention_time'], name='peak_result_result__490ac8_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['report_id'], name='report_report__e1c2a7_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['analysis_type', 'department', '-report_id'], name='report_analysi_0bf6bf_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['project_id'], name='report_project_132bc4_idx'),
        ),
        migrations.AddIndex(
            model_name='samplemetadata',
            index=models.Index(fields=['result_id'], name='sample_meta_result__a86884_idx'),
        ),
        migrations.AddIndex(
            model_name='samplemetadata',
            index=models.Index(fields=['sample_name'], name='sample_meta_sample__f99209_idx'),
        ),
        migrations.AddIndex(
            model_name='samplemetadata',
            index=models.Index(fields=['sample_set_name'], name='sample_meta_sample__44c6aa_idx'),
        ),
        migrations.AddIndex(
            model_name='samplemetadata',
            index=models.Index(fields=['sample_type', 'sample_name', '-date_acquired'], name='sample_meta_sample__f2dc79_idx'),
        ),
        migrations.AddIndex(
            model_name='samplemetadata',
            index=models.Index(fields=['sample_set_name', 'sample_prefix'], name='sample_meta_sample__c911bc_idx'),
        ),
        migrations.AddIndex(
            model_name='timeseriesdata',
            index=models.Index(fields=['result_id'], name='time_series_result__093e9b_idx'),
        ),
        migrations.AddIndex(
            model_name='timeseriesdata',
            index=models.Index(fields=['result_id', 'time'], name='time_series_result__28e03a_idx'),
        ),
    ]
